[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["derivative*"]

[project]
name = "derivative"
dynamic = ["version"]
description = "Numerical differentiation in python."
readme = "README.rst"
requires-python = ">=3.9"
license-files = ["LICENSE.rst"]
authors = [
    { name = "Andy Goldschmidt", email = "andygold@uchicago.edu" },
    { name = "Markus Quade", email = "info@markusqua.de" },
    { name = "Jacob Stevens-Haas", email = "jmsh@uw.edu" },
]
keywords = ["differentiation", "derivative", "gradient", "prime"]
dependencies = [
    "numpy>=1.18.3",
    "scipy>=1.4.1",
    "scikit-learn>=1.0.0",
    "importlib-metadata>=7.1.0",
    "spectral-derivatives>=0.8",
]

[project.optional-dependencies]
docs = [
    "sphinx==7.2.6",
    "nbsphinx==0.9.5",
    "matplotlib",
    "ipython",
    "ipykernel",
]
dev = [
    "asv",
    "pytest>=7",
]

[project.urls]
Repository = "https://github.com/andgoldschmidt/derivative"
Documentation = "https://derivative.readthedocs.io/"

[tool.setuptools_scm]
write_to = "derivative/__version__.py"

[project.entry-points."derivative.hyperparam_opt"]
"kalman.default" = "derivative.utils:_default_kalman"
