name: Test

# Push/pull overlap if PR is from the same repo,
#  but pull_request is nec. for forks, etc.
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      # ======
      # Checkout, set up python and uv
      # ======
      - name: Check out
        uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      - name: Install dependencies
        run: uv pip install .[dev]
      # ======
      # Run test suite
      # TODO: output code coverage, --cov=<project-dir> --cov-report=xml
      # https://github.com/marketplace/actions/install-poetry-action#codecov-upload
      # ======
      - name: Run tests
        run: pytest

  benchmarks:
    name: ASV Benchmarks
    needs: test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      # ======
      # Checkout, set up python
      # ======
      - name: Check out
        uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      - name: Install dependencies
        run: uv pip install .[dev]
      # ======
      # Compare benchmarks between master and PR, and fail if any get worse
      # ======
      - name: Setup ASV
        run: |
          cd asv_bench
          asv machine --yes
      - name: Check regression
        run: |
          cd asv_bench
          git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:pr
          asv continuous base pr -e
