name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Deploy release to PyPI
    runs-on: ubuntu-latest
    environment:
#      name: testpypi
      name: release
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      # ======
      # Checkout, set up python and uv
      # ======
      - name: Check out
        uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      # ======
      # Build and upload package to Test-PyPI
      #  uv build
      #  uv publish --repository testpypi --token ${{ secrets.TEST_PYPI_TOKEN }}
      # =====
      - name: Upload package
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}
          
